@startuml
!include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title PKB Overview

node "Inserter" as Inserter

database "Storage" as Storage {
  [AST]
  frame "Manager" {
    [Entity Manager]
    [Abstraction Manager]
  }
}

node "Responder" as Responder

Inserter -[hidden]-> AST
Inserter -[hidden]-> [Entity Manager]
Inserter -[hidden]-> [Abstraction Manager]
AST -[hidden]-> Responder
[Entity Manager] -[hidden]-> Responder
[Abstraction Manager] -[hidden]-> Responder

@end
