@startuml
!include ../style.puml
skinparam ClassFontColor #000000


skinparam ClassBorderColor #000000
box QPS LOGIC_COLOR_T1
participant ":QueryDriver" as QueryDriver LOGIC_COLOR
participant ":QueryParser" as QueryParser LOGIC_COLOR
participant "o:QueryObject" as QueryObject LOGIC_COLOR
participant ":QueryBuilder" as QueryBuilder LOGIC_COLOR
participant "t:DataAccessLayer" as DataAccessLayer LOGIC_COLOR
participant "r:ResultsHandler" as ResultsHandler LOGIC_COLOR
end box

[-> QueryDriver : executeQuery(String query)
activate QueryDriver

QueryDriver -> QueryParser : generateQueryObjects(String query)
activate QueryParser

create QueryObject
QueryParser -> QueryObject : parse()
activate QueryObject

QueryObject --> QueryParser : o
deactivate QueryObject

QueryParser -> QueryBuilder : buildQuery(vector<QueryObject> o)
activate QueryBuilder

QueryBuilder -> DataAccessLayer : callPKBAPI(...args*)
activate DataAccessLayer

DataAccessLayer --> QueryBuilder : t
deactivate DataAccessLayer

QueryBuilder --> ResultsHandler : processTuples(vector<Tuples> tuples)
activate ResultsHandler

ResultsHandler --> QueryBuilder : r
deactivate ResultsHandler

QueryBuilder --> QueryParser : r
deactivate QueryBuilder

QueryParser --> QueryDriver : r
deactivate QueryParser

[<--QueryDriver
deactivate QueryDriver

@end