@startuml

title DesignExtractor Overview

package DesignExtractor <<Rectangle>> {
    note left of DesignExtractor
    Shorthand for types used:
    @ - Shared Pointer, str - String, b - Bool,
    strv - String View, v - vector, ∅ - void,
    u_set - u_set
    end note
    Class DesignExtractor {
        -@EntityExtractor entityExtractor
        -@ModifiesExtractor modifiesExtractor
        -@UsesExtractor usesExtractor
        -@ParentsExtractor parentsExtractor
        -@FollowsExtractor followsExtractor
        -@CallsExtractor callsExtractor
        -@NextExtractor nextExtractor
        -@ProcedureLineNumberExtractor procedureLineNumberExtractor
        +void extractAndInsertAll(@ProcessedProgram, b useMultithread)
    }

    Abstract Extractor <<Base>> {
        +void extract(@ProcessedProgram)
        +void extract(@ProcessedProcedure)
        +void extract(@ProcessedStmtList)
        ---
        {abstract more extract methods}
    }
    Class EntityExtractor {
        - procedureMap: @map<str, u_set<str>>
        - variableMap: @map<str, u_set<str>>
        - statementMap: @map<str, u_set<str>>
        - constantMap: @map<str, u_set<str>>
        - callProcNameMap: @map<str, u_set<str>>
        - readVarNameMap: @map<str, u_set<str>>
        - printVarNameMap: @map<str, u_set<str>>
        - patternMap: @map<str, @Node>>
        +void extract(@ProcessedProgram) override
        +void extract(@ProcessedProcedure) override
        +void extract(@ProcessedStmtList) override
        +@map<str, u_set<str>> getProcedureMap()
        ---
        {abstract more overridden extract, getMap methods}
    }

    package AbstractionExtractors {
        Abstract AbstractionExtractor {
            +virtual void extractAbstractions(@ProcessedProgram)
            +void extract(@ProcessedProgram) override
            +void extract(@ProcessedProcedure) override
            +void extract(@ProcessedStmtList) override
            +@map<str, u_set<str>> getStorageMap()
            #@map<str, u_set<str> AbstractionStorageMap
            ---
            {abstract more extract methods}
        }
        note right of AbstractionExtractor
        Further expanded in
        another file
        end note
    }
    
    

    DesignExtractor ..> Extractor
    Extractor <|-left- EntityExtractor
    Extractor <|-- AbstractionExtractor
    
}
@enduml