    AssignKeywordToken -up-|> KeywordToken
    CallKeywordToken -up-|> KeywordToken
    ConstantKeywordToken -up-|> KeywordToken
    ElseKeywordToken -up-|> KeywordToken
    IfKeywordToken -up-|> KeywordToken
    PrintKeywordToken -left-|> KeywordToken
    ProcedureKeywordToken -left-|> KeywordToken
    ReadKeywordToken -left-|> KeywordToken
    StmtKeywordToken -right-|> KeywordToken
    ThenKeywordToken -right-|> KeywordToken
    VariableKeywordToken -right-|> KeywordToken
    WhileKeywordToken -down-|> KeywordToken
    SelectKeywordToken -down-|> KeywordToken