@startuml
!include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title SPA Overview

Program -down-> SP
SP -down-> PKB : design abstractions
PKB -right-> QPS : design abstractions
Program -right-> UI
UI -down-> QPS : PQL query
QPS -up-> UI : query result

@end
