@startuml
' !include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title QPS Overview

' package QueryProcessingSubsystem <<Rectangle>> {
    
' }
' Class Tokens {
        
' }
package QPS <<Rectangle>> {
    'Tokenizes the query'
    ' Class Tokenizer {
    '     vector<Tokens> tokens
    ' }
    'Represents the different types of tokens'
    
    Class QueryDriver {
        String Query
        QueryParser queryParser
    }

    'Converts the Tokens into Query Object'
    Class QueryParser {
        vector<QueryObject> generateQueryObjects(String query)
        
    }

    'AST representation of tokens'
    ' Class AST'

    'Holds the info needed to request the PKB'
    Class QueryObject {
        parse()
    }
    Class Uses
    Class Modifies
    Class Others
    
    'builds the query based on Query Object (which API calls to make to PKB)'
    Class QueryBuilder {
        vector<QueryObject>
        void buildQuery(vector<QueryObject> o)
    }
    'Handles return values from PKB'
    Class ResultsHandler {
        String processTuples(vector<Tuples> tuples)
    }

    'Talks to PKB'
    Class DataAccessLayer {
        
        vector<Tuples> callPKBAPI(...args*)
    }

    

}


Uses -up-|> QueryObject
Modifies -up-|> QueryObject
Others -up-|> QueryObject
QueryParser .down.> QueryObject
DataAccessLayer .left.> QueryObject
QueryBuilder .right.> QueryObject
QueryDriver ..> QueryParser
' QueryProcessingSubsystem -down-> QPS
' Clauses -up-|> QueryEvaluator

@end
