@startuml
!include ../../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
box SimpleTokenizer LOGIC_COLOR_T1
participant "SimpleTokenizer" as SimpleTokenizer LOGIC_COLOR
end box

[-> SimpleTokenizer : tokenizeProgram(String src)
activate SimpleTokenizer

SimpleTokenizer -> SimpleTokenizer : <<static>>\n outermostScopeDetector()
activate SimpleTokenizer
SimpleTokenizer -> SimpleTokenizer : locations of { } for procedures
deactivate SimpleTokenizer

loop until no more procedures
    SimpleTokenizer -> SimpleTokenizer : <<static>>\n processPreProcedureDetails()
    activate SimpleTokenizer
    SimpleTokenizer -> SimpleTokenizer : procedure name
    deactivate SimpleTokenizer
    SimpleTokenizer -> SimpleTokenizer : <<static>>\n tokenizeStmtList()
    activate SimpleTokenizer
    SimpleTokenizer -> SimpleTokenizer : <<static>>\n outermostScopeDetector()
    activate SimpleTokenizer
    SimpleTokenizer -> SimpleTokenizer : locations of { } for if/while statements
    deactivate SimpleTokenizer
    loop until no more if/while statements
        SimpleTokenizer -> SimpleTokenizer : <<static>>\n tokenizeSemicolonStatement()
        activate SimpleTokenizer
        SimpleTokenizer -> SimpleTokenizer : tokenized statements that \nare before if/while statements
        deactivate SimpleTokenizer
        SimpleTokenizer -> SimpleTokenizer : <<static>>\n processConditionalDeclaration()
        activate SimpleTokenizer
        SimpleTokenizer -> SimpleTokenizer
        deactivate SimpleTokenizer
        SimpleTokenizer -> SimpleTokenizer : <<static>>\n tokenizeStmtList()
        activate SimpleTokenizer
        SimpleTokenizer -> SimpleTokenizer : tokenized then/while block
        deactivate SimpleTokenizer
        alt if statement 
            SimpleTokenizer -> SimpleTokenizer : <<static>>\n tokenizeStmtList()
            activate SimpleTokenizer
            SimpleTokenizer -> SimpleTokenizer : tokenized else block
            deactivate SimpleTokenizer
        end
    end
    SimpleTokenizer -> SimpleTokenizer : <<static>>\n tokenizeSemicolonStatement()
    activate SimpleTokenizer
    SimpleTokenizer -> SimpleTokenizer : tokenized remaining statements
    deactivate SimpleTokenizer

    SimpleTokenizer -> SimpleTokenizer : tokenized procedure statement list
    deactivate SimpleTokenizer
end
[<--SimpleTokenizer : TokenizedProgram
deactivate SimpleTokenizer

@end