@startuml
' !include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title SIMPLE Tokenizer Results

Class TokenizedProgram {
    - v<@TokenizedProcedure> procedures
    + v<@TokenizedProcedure> getAllProcedures()
    + bool equalsTo(TokenizedProgram)
}

Class TokenizedProcedure {
    - string procedureName
    - @TokenizedStmtList statementList
    + string getName()
    + @TokenizedStmtList getStmts()
    + bool equalsTo(TokeniszedProcedure)
}

Class TokenizedStmtList {
    - v<@TokenizedStmt> statements
    + v<@TokenizedStmt> getStmts()
    + bool equalsTo(TokenizedStmtList)
}

Class TokenizedStmt {
    - const int statementNumber
    + int getStatementNumber()
    + bool equalsTo(TokenizedStmt)
}

Class TokenizedSemicolonStmt {
    - v<@Token> contents
    + v<@Token> getContents()
    + bool equalsTo(TokenizedSemicolonStmt)
}

Class TokenizedConditionalStmt {
    - v<@Token> conditionalExp
    + v<@Token> getConditionalExp()
    + bool equalsTo(TokenizedConditionalStmt)
}

Class TokenizedIfStmt {
    - @TokenizedStmtList thenBlock
    - @TokenizedStmtList elseBlock
    + @TokenizedStmtList getThenBlock()
    + @TokenizedStmtList getElseBlock()
    + bool equalsTo(TokenizedIfStmt)
}

Class TokenizedWhileStmt {
    - @TokenizedStmtList whileBlock
    + @TokenizedStmtList getWhileBlock()
    + bool equalsTo(TokenizedWhileStmt)
}
TokenizedProgram *-- TokenizedProcedure
TokenizedProcedure *-- TokenizedStmtList
TokenizedStmtList *-- TokenizedStmt
TokenizedIfStmt *-- TokenizedStmtList
TokenizedWhileStmt *-- TokenizedStmtList

TokenizedIfStmt <|-- TokenizedConditionalStmt
TokenizedWhileStmt <|-- TokenizedConditionalStmt
TokenizedConditionalStmt <|-- TokenizedStmt
TokenizedSemicolonStmt <|-- TokenizedStmt

@end