name: Team18_CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:

  cpplint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install cpplint
    - run: cpplint --recursive .
  
  build-VS-2022:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.3
      
      - name: Use NuGet 6.7.0
        uses: nuget/setup-nuget@v1
        with: 
          nuget-version: '6.7.0'
      
      - name: Print current directory
        run: dir
      
      - name: Change directory
        run: |
            cd Team18/Code18
            dir
     
      - name: Restore nuget packages for all solutions
        run: msbuild 'Team18/Code18/StartupSPASolution.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }} /t:restore
      
      - name: Build solution
        run: msbuild 'Team18/Code18/StartupSPASolution.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}  
  
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{env.INSTALL_LOCATION}}
        key: ${{runner.os}}-dependencies

    - name: install GoogleTest
      if: ${{steps.cache.output.cache-hit != 'true'}}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION" -Dgtest_force_shared_crt=1
        cmake --build build --config Release
        cmake --build build --target install --config Release
        cd ../23s1-win-spa-team-18

    - name: configure
      run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION"
      
    - name: build
      run: cmake --build build --config "$env:BUILD_TYPE" -j4

    - name: run tests
      run: |
        cd build
        ctest -C "$env:BUILD_TYPE" -VV

    - name: print current directory
      run: |
         dir
         cd build
         dir
         cd Team18/Code18
         dir
         #cd Release
         #./Autotester ../Team18/Code18/SystemTesting/no_clauses_source.txt ../Team18/Code18/SystemTesting/no_clauses_queries.txt out.xml